FROM golang:1.20-alpine AS build
WORKDIR /app
COPY . .
RUN apk add --no-cache git
RUN CGO_ENABLED=1 GOOS=linux go build -o /bin/api ./cmd/api

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/api /bin/api
WORKDIR /
CMD ["/bin/api"]
