FROM golang:1.20-alpine AS build
WORKDIR /app
COPY . .
RUN apk add --no-cache git
RUN CGO_ENABLED=1 GOOS=linux go build -o /bin/worker ./cmd/worker

FROM alpine:3.18
RUN apk add --no-cache ca-certificates
COPY --from=build /bin/worker /bin/worker
WORKDIR /
CMD ["/bin/worker"]
